### ISSUE TITLE
328P HEX NEEDED

### ISSUE THREAD

**Issue by dunk8888** [mic159/Pong_Clock#1]
Hi mike,is it possible i could trouble you for the hex file of pong clock,i cant seem to get it to compile,ive added libraries etc but errors,ime not to good yet with code.thanks dunkyoung25@gmail.com

**Comment by mike-rankin** [comment]
I've had so many problems with compile errors because of IDE changes and library updates but I can try compiling tonight. How do I create a .hex file using the IDE?

**Comment by mic159** [comment]
Sure, I'll make one today (probably tonight).

I'm pretty sure the IDE puts the hex files in a temporary directory somewhere, I'll find it.

The I will create a github release and upload it there.

**Comment by mike-rankin** [comment]
Created one but have not tested it.

**Comment by mic159** [comment]
I have updated the code to work on Arduino IDE 1.6.12, but cant test it till I get home (where the clock is).

It (should) work with the official libraries of the dependencies now, so you can use the Arduino library manager.
I noted the exact version numbers I used today for furure reference too.

When I get home I will test it out, then upload the .hex to github

**Comment by dunk8888** [comment]
Hi i only just read all your messages,sorry i didnt see them,right ive
compiled my own thanks,all sorted now,keep up the nice work,and thanks
again for your time ;-)

**Comment by mic159** [comment]
@dunk8888 I have updated the code to work with the latest libraries and IDE.
The HEX files are also now available to download at https://github.com/mic159/Pong_Clock/releases/tag/v1.0.0

Enjoy!
